name: Feature request
description: Suggest an improvement to Babysitter
title: "[Feature]: "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the idea. The more concrete the workflow and examples, the easier it is to evaluate.

  - type: textarea
    id: problem
    attributes:
      label: Problem / motivation
      description: What are you trying to do, and what’s painful today?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What should Babysitter do? Include UI/command ideas when useful.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Screenshots, sample `.a5c/runs` structure, or logs (redact secrets).
    validations:
      required: false

